services:
  - type: web
    name: audio-transcriber
    env: python
    plan: free
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 200
    envVars:
      PYTHON_VERSION: 3.10.13
